spring.application.name=onyxbackend

# PostgreSQL Database Configuration
# Change 'your_password' to your actual postgres password
spring.datasource.url=jdbc:postgresql://localhost:5432/onyx_db
spring.datasource.username=postgres
spring.datasource.password=82786
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ddl-auto=update tells Spring to automatically create/update tables in Postgres for you
spring.jpa.hibernate.ddl-auto=update
# Shows the SQL queries in the console (helpful for debugging!)
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.type.json_format_mapper=org.hibernate.type.format.jackson.JacksonJsonFormatMapper